### ISSUE TITLE
make ddtrace optional

### ISSUE THREAD

**Issue by grosser** [zendesk/iron_bank#2]
would be nice if it was not required since not everyone uses datadog

**Comment by mickaelpham** [comment]
`v1.0.1` removed the `Datadog.configure` block from the gem initializer: https://github.com/zendesk/iron_bank/commit/afb4cee3a7bfdd1d5472e0b65448c842b118b4f8.

Next step is to make `IronBank::OpenTracing` and its associated `ddtrace` dependency optional.

cc: @mustafaturan
