### ISSUE TITLE
IronBank Across Multiple Zuora Environments

### ISSUE THREAD

**Issue by Nerdenberger** [zendesk/iron_bank#32]
Hey folks, 

How would you implement the IronBank gem to work across multiple Zuora environments?  

I'm implementing Zuora, and working on tooling that maintains product books between sandbox / production instances. 

I basically just need multiple instances of IronBank with different configs.

**Comment by mickaelpham** [comment]
Hi @Nerdenberger 

Sorry for the late response. Very happy to hear that you use (or have considered using) IronBank!

> How would you implement the IronBank gem to work across multiple Zuora environments?

Short answer: I'd consider re-configuring the `IronBank.client` when changing environment. Here's a snippet on how it could work:

```rb
# helper methods
def reset_iron_bank
  IronBank.remove_instance_variable(:@client)
end

def use_sandbox
  reset_iron_bank
  ::IronBank.configure do |config|
    # configuration for sandbox
  end
end

def use_production
  reset_iron_bank
  ::IronBank.configure do |config|
    # configuration for production
  end
end

# usage example
use_sandbox
sandbox_product = IronBank::Product.find(sandbox_product_id)
use_production
production_product = IronBank::Product.find(production_product_id)

# compare product code here
```

Long answer: unfortunately, the initial architecture of `iron_bank` does not work very well with **multiple instances**.

When I considered how to handle authentication / client instances, I looked at Octokit (https://github.com/octokit/octokit.rb#authentication) but I was not happy with the idea of having to call `client#product`, etc.

I preferred to write something closer to `ActiveRecord`, using the pattern of `IronBank::<Resource>`. I was then faced with the question of: how to pass a client/session to that resource?

Option A was to have the following signature:

```rb
IronBank::Product.find(client, conditions)
```

Option B, which become the chosen solution, was to have a global `IronBank.client` that these resources could reference. I knew this would affect the capability of having **multiple instances** of IronBank in the same process, but I liked the simplicity of not having to pass around an `IronBank::Client` instance.

I also liked the configuration block approach over the client initialization, following [this article from Thoughbot](https://thoughtbot.com/blog/mygem-configure-block).

**Anyway, back to the point.**

Please note that there might be other memoization patterns that need to be reset in the `reset_iron_bank` helper method. I believe this would be the case if your **schemas** differ between apisandbox and production (like a different custom field API name).

I'd be happy to hear back if this approach worked for you. Again, sorry for the late answer.

Best
